# Generated by Django 3.1.7 on 2021-05-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210504_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Images11',
            field=models.ImageField(blank=True, upload_to='photos/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='Images22',
            field=models.ImageField(blank=True, upload_to='photos/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='Images33',
            field=models.ImageField(blank=True, upload_to='photos/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='Images44',
            field=models.ImageField(blank=True, upload_to='photos/products'),
        ),
    ]
