# Generated by Django 3.1.7 on 2021-05-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210506_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Images33',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Images44',
        ),
        migrations.AlterField(
            model_name='product',
            name='Images11',
            field=models.ImageField(upload_to='photos/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Images22',
            field=models.ImageField(upload_to='photos/products'),
        ),
    ]
