# Generated by Django 3.1.7 on 2021-05-21 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210521_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discounted_price',
            new_name='price_before_discount',
        ),
    ]
