# Generated by Django 3.1.7 on 2021-05-29 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_reviewrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_discount',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
