# Generated by Django 3.1.7 on 2021-05-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='https://moonvillageassociation.org/wp-content/uploads/2018/06/default-profile-picture1.jpg', upload_to='userprofile'),
        ),
    ]
