# Generated by Django 3.1.7 on 2021-05-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profilereferral'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referral_count',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
