# Generated by Django 3.1.7 on 2021-05-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210510_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('PAYPAL', 'PAYPAL')], default='COD', max_length=20),
        ),
    ]
